# On utilise une image Docker contenant Java et Maven
image: maven:3.9-eclipse-temurin-25-alpine

# Cache pour ne pas retélécharger les dépendances .m2 à chaque fois
cache:
  paths:
    - .m2/repository

variables:
  # On dit à Maven d'utiliser le dossier local pour le cache
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  
  MAVEN_SILENCE_FLAGS: "-Dspring.main.banner-mode=off -Dlogging.level.root=WARN -Dlogging.level.org.hibernate.SQL=WARN -Dlogging.level.org.hibernate.type.descriptor.sql=WARN -Dspring.jpa.show-sql=false -Dspring.jpa.properties.hibernate.show_sql=false -Dlogging.level.fr.uge.forkeat.infrastructure.persistence.sync=WARN -Dlogging.level.org.springframework.data.neo4j=ERROR"

stages:
  - build
  - test
  - deploy

# 1. Compilation du code source
compilation:
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH == "develop" && $CI_PIPELINE_SOURCE == "push"
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop" && $CI_PIPELINE_SOURCE == "merge_request_event"
  script:
    - cd backend && mvn clean compile

# 2. Exécution des tests unitaires
unit-tests:
  stage: test
  rules:
    - if: $CI_COMMIT_BRANCH == "develop" && $CI_PIPELINE_SOURCE == "push"
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop" && $CI_PIPELINE_SOURCE == "merge_request_event"
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_TLS_CERTDIR: ""
  services:
    - docker:dind
  before_script:
    - apk add --no-cache docker docker-compose
    # Copier le fichier .env à partir des variables GitLab CI/CD
    - cp $TESTS_DOTENV_FILE backend/.env
  script:
    - cd backend && mvn test $MAVEN_SILENCE_FLAGS

build-and-push-api:
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == "push"
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_TLS_CERTDIR: ""
  services:
    - docker:dind
  before_script:
    - apk add --no-cache docker docker-compose
    - echo "$DEPLOY_TOKEN_PASSWORD" | docker login -u "$DEPLOY_TOKEN_USERNAME" --password-stdin registry.gitlab.com
  script:
    - cd backend && docker build -t registry.gitlab.com/adben27/projet-recettes-uge .
    - docker push registry.gitlab.com/adben27/projet-recettes-uge

deploy-prod:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == "push"
  before_script:
    - apk add --no-cache openssh-keygen openssl
    - mkdir -p ~/.ssh
    - echo "$DEPLOY_SSH_PRIVATE_KEY" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H $DEPLOY_SERVER_IP >> ~/.ssh/known_hosts
    - scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no $PROD_DOTENV_FILE $DEPLOY_SERVER_USERNAME@$DEPLOY_SERVER_IP:/home/$DEPLOY_SERVER_USERNAME/projet-recettes-uge/backend/.env
  script:
    - ssh -i ~/.ssh/id_rsa $DEPLOY_SERVER_USERNAME@$DEPLOY_SERVER_IP "cd /home/$DEPLOY_SERVER_USERNAME/projet-recettes-uge/backend && git fetch origin $CI_COMMIT_BRANCH && git reset --hard origin/$CI_COMMIT_BRANCH && docker login registry.gitlab.com -u $DEPLOY_TOKEN_USERNAME -p $DEPLOY_TOKEN_PASSWORD && docker compose -f docker-compose.yml -f docker-compose.prod.yml down && docker compose -f docker-compose.yml -f docker-compose.prod.yml up --build -d"
  after_script:
    - rm -f ~/.ssh/id_rsa
