# Sink configuration
debezium.sink.type=kafka
debezium.sink.kafka.producer.bootstrap.servers=kafka:29092
debezium.sink.kafka.producer.acks=all
debezium.sink.kafka.producer.retries=3
debezium.sink.kafka.producer.enable.idempotence=true
debezium.sink.kafka.producer.key.serializer=org.apache.kafka.common.serialization.StringSerializer
debezium.sink.kafka.producer.value.serializer=org.apache.kafka.common.serialization.StringSerializer


# Source configuration
debezium.source.connector.class=io.debezium.connector.postgresql.PostgresConnector
debezium.source.offset.storage.file.filename=/debezium/data/offsets.json
debezium.source.offset.flush.interval.ms=1000
debezium.source.database.hostname=postgres
debezium.source.database.port=5432
debezium.source.database.user=${POSTGRES_USER}
debezium.source.database.password=${POSTGRES_PASSWORD}
debezium.source.database.dbname=${POSTGRES_DB}
debezium.source.topic.prefix=forkeat
debezium.source.table.include.list=public.users,public.recipes,public.super_likes
debezium.source.column.exclude.list=public.users.password
debezium.source.plugin.name=pgoutput
debezium.source.publication.autocreate.mode=filtered
debezium.source.slot.name=forkeat_slot
debezium.source.snapshot.mode=initial
# Pas de tombstones
debezium.source.tombstones.on.delete=false 

# Format JSON
debezium.format.key=json
debezium.format.value=json
debezium.format.key.schemas.enable=false
debezium.format.value.schemas.enable=false

# Quarkus configuration (exclut)

