spring.application.name=ForkEat


app.admin.password=${ADMIN_PASSWORD}
app.admin.username=admin
# Server
server.port=8080

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/${POSTGRES_DB}?stringtype=unspecified
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.globally_quoted_identifiers=true
spring.jpa.open-in-view=false

# Flyway
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=0
spring.flyway.locations=classpath:db/migration

# Neo4j
spring.neo4j.uri=bolt://localhost:7687
spring.neo4j.authentication.username=${NEO4J_USER}
spring.neo4j.authentication.password=${NEO4J_PASSWORD}

# Debezium Embedded
debezium.enabled=true
debezium.offset-storage-file=./debezium-offsets.dat
debezium.database.hostname=localhost
debezium.database.port=5432
debezium.database.user=${POSTGRES_USER}
debezium.database.password=${POSTGRES_PASSWORD}
debezium.database.dbname=${POSTGRES_DB}


# Logging
logging.level.root=INFO
logging.level.fr.uge.forkeat=DEBUG
logging.level.org.flywaydb=INFO

# --- STRIPE ---
stripe.api.key=${STRIPE_API_KEY}
stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET}

# Multipart (file uploads)
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
server.tomcat.max-swallow-size=-1
server.tomcat.max-parameter-count=1000
server.tomcat.max-http-form-post-size=-1
spring.mvc.async.request-timeout=-1
spring.servlet.multipart.location=./uploads
logging.level.org.springframework.web=DEBUG
server.tomcat.max-part-count=100
server.tomcat.max-part-header-size=2048

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8

# --- APPLICATION ---
app.front.url=http://localhost:4200

app.jwt.secret=${JWT_SECRET}
app.jwt.expiration=600000

# OAUTH2
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=profile,email
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=forkeat.noreply@gmail.com
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Email verification
app.base-url=http://localhost:8080
app.email.confirmation-expiry-hours = 24
app.email.code-expiry-minutes = 10


# --- R2 Storage ---
#cloudflare.r2.account.id: ${CLOUDFLARE_ACCOUNT_ID}
cloudflare.r2.access.key.id: ${R2_ACCESS_KEY_ID}
cloudflare.r2.secret.access.key: ${R2_SECRET_ACCESS_KEY}
cloudflare.r2.bucket.name: forkeat-images
cloudflare.r2.endpoint: https://${CLOUDFLARE_ACCOUNT_ID}.r2.cloudflarestorage.com
cloudflare.r2.public.url= ${R2_PUBLIC_URL:https://pub-xxxxx.r2.dev}
cloudflare-r2-limit-size-image: 5
